name: mon_assessment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_maps_flutter: ^2.11.0
  custom_info_window: ^1.0.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/json/


  fonts:
    - family: EuclidCircular
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Bold-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
        - asset: assets/fonts/Euclid-Circular-A-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Light-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Light.ttf
        - asset: assets/fonts/Euclid-Circular-A-Medium.ttf
        - asset: assets/fonts/Euclid-Circular-A-Medium-Italic.ttf
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/Euclid-Circular-A-Semibold.ttf
        - asset: assets/fonts/Euclid-Circular-A-Semibold-Italic.ttf


